# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DDI', models.CharField(max_length=200)),
                ('extention', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('manu', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='extension',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Phone'),
        ),
    ]
